name: My DockerImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image of mine
      run: docker build . --file Dockerfile --tag my123:123
    - name: uploading12345
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: harshametla/docker_image
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
